//----------------------------------------------------------------------------------------------------------------------------
// Autogenerated file -- DO NOT EDIT
//
// This file was autogenerated by PeakRDL-svh
// Date (mm-dd-yyyy) : 02-10-2022  
// Time (hh:mm:ss)   : 00:17:30
//
// This package file includes the required define files
//----------------------------------------------------------------------------------------------------------------------------

`ifndef _EXAMPLE_REGISTER_DEFINES_PKG_INCLUDED_
`define _EXAMPLE_REGISTER_DEFINES_PKG_INCLUDED_

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Package: example_register_defines_pkg
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

package example_register_defines_pkg;

  import uvm_pkg::*;
  `include "uvm_macros.svh"

  `include "spi_master_defines.svh"
endpackage: example_register_defines_pkg

`endif

