+incdir+../../src/dv/hvl_top/test/sequences/master_sequences/
+incdir+../../src/dv/hvl_top/test/sequences/slave_sequences/
+incdir+../../src/dv/hvl_top/test/virtual_sequences/
+incdir+../../src/dv/apb_avip/src/hvl_top/master/
+incdir+../../src/dv/spi_avip/src/hvl_top/slave/
+incdir+../../src/dv/hvl_top/env/virtual_sequencer/
+incdir+../../src/dv/hvl_top/env/
+incdir+../../src/dv/hvl_top/test/
../../src/dv/apb_avip/src/globals/apb_global_pkg.sv
../../src/dv/spi_avip/src/globals/spi_globals_pkg.sv
../../src/dv/apb_avip/src/hvl_top/master/apb_master_pkg.sv
../../src/dv/spi_avip/src/hvl_top/slave/spi_slave_pkg.sv
../../src/dv/hvl_top/test/sequences/master_sequences/apb_master_seq_pkg.sv
../../src/dv/hvl_top/test/sequences/slave_sequences/spi_slave_seq_pkg.sv
../../src/dv/hvl_top/env/pulpino_spi_master_ip_env_pkg.sv
../../src/dv/hvl_top/test/virtual_sequences/pulpino_spi_master_ip_virtual_seq_pkg.sv
../../src/dv/hvl_top/test/pulpino_spi_master_ip_test_pkg.sv
../../src/dv/apb_avip/src/hdl_top/apb_if/apb_if.sv
../../src/dv/spi_avip/src/hdl_top/spi_interface/spi_if.sv
../../src/dv/apb_avip/src/hdl_top/master_agent_bfm/apb_master_agent_bfm.sv
../../src/dv/apb_avip/src/hdl_top/master_agent_bfm/apb_master_driver_bfm.sv
../../src/dv/apb_avip/src/hdl_top/master_agent_bfm/apb_master_monitor_bfm.sv
../../src/dv/spi_avip/src/hdl_top/slave_agent_bfm/slave_agent_bfm.sv
../../src/dv/spi_avip/src/hdl_top/slave_agent_bfm/slave_driver_bfm.sv
../../src/dv/spi_avip/src/hdl_top/slave_agent_bfm/slave_monitor_bfm.sv
../../src/dv/hdl_top/hdl_top.sv
../../src/dv/hvl_top/hvl_top.sv


