+incdir+../../src/dv/hvl_top/test/sequences/master_sequences/
+incdir+../../src/dv/hvl_top/test/sequences/slave_sequences/
+incdir+../../src/dv/hvl_top/test/reg_sequences/
+incdir+../../src/dv/hvl_top/test/virtual_sequences/
+incdir+../../src/dv/hvl_top/apb_master_agent/
+incdir+../../src/dv/hvl_top/spi_slave_agent/
+incdir+../../src/dv/hvl_top/env/virtual_sequencer/
+incdir+../../src/dv/hvl_top/env/
+incdir+../../src/dv/hvl_top/test/
+incdir+../../src/dv/systemRDL
+incdir+../../src/dv/systemRDL/output
../../src/dv/globals/apb_master_global_pkg.sv
../../src/dv/globals/spi_slave_global_pkg.sv
../../src/dv/hvl_top/apb_master_agent/apb_master_pkg.sv
../../src/dv/hvl_top/spi_slave_agent/spi_slave_pkg.sv
../../src/dv/systemRDL/output/spi_master_defines_pkg.svh
../../src/dv/systemRDL/output/spi_master_uvm_pkg.sv
../../src/dv/hvl_top/test/reg_sequences/apb_reg_seq_pkg.sv
../../src/dv/hvl_top/test/sequences/master_sequences/apb_master_seq_pkg.sv
../../src/dv/hvl_top/test/sequences/slave_sequences/spi_slave_seq_pkg.sv
../../src/dv/hvl_top/env/pulpino_spi_master_ip_env_pkg.sv
../../src/dv/hvl_top/test/virtual_sequences/pulpino_spi_master_ip_virtual_seq_pkg.sv
../../src/dv/hvl_top/test/pulpino_spi_master_ip_test_pkg.sv
../../src/dv/hdl_top/apb_if/apb_if.sv
../../src/dv/hdl_top/spi_if/spi_if.sv
../../src/dv/hdl_top/apb_master_agent_bfm/apb_master_agent_bfm.sv
../../src/dv/hdl_top/apb_master_agent_bfm/apb_master_driver_bfm.sv
../../src/dv/hdl_top/apb_master_agent_bfm/apb_master_monitor_bfm.sv
../../src/dv/hdl_top/spi_slave_agent_bfm/spi_slave_agent_bfm.sv
../../src/dv/hdl_top/spi_slave_agent_bfm/spi_slave_driver_bfm.sv
../../src/dv/hdl_top/spi_slave_agent_bfm/spi_slave_monitor_bfm.sv
../../src/dv/hdl_top/hdl_top.sv
../../src/dv/hvl_top/hvl_top.sv


