+incdir+../../src/globals/
+incdir+../../src/hvl_top/slave
+incdir+../../src/hvl_top/test/slave_sequences
+incdir+../../src/hdl_top/slave_agent_bfm
+incdir+../../src/hdl_top/spi_interface
../../src/globals/spi_globals_pkg.sv
../../src/hvl_top/slave/spi_slave_pkg.sv
../../src/hvl_top/test/slave_sequences/spi_slave_seq_pkg.sv
../../src/hdl_top/spi_interface/spi_if.sv
../../src/hdl_top/slave_agent_bfm/slave_driver_bfm.sv
../../src/hdl_top/slave_agent_bfm/slave_monitor_bfm.sv
../../src/hdl_top/slave_agent_bfm/slave_agent_bfm.sv
../../src/hdl_top/hdl_top.sv
